### ISSUE TITLE
How to allocate multiple GPUs to a virtual machine

### ISSUE THREAD

**Issue by ZP-AlwaysWin** [NVIDIA/kubevirt-gpu-device-plugin#10]
How to allocate multiple GPUs to a virtual machine
```
gpus:
          - deviceName: nvidia.com/TU104GL_Tesla_T4
            name: gpu1
          type: ""
        memory:
          guest: 8Gi
        resources:
          limits:
            nvidia.com/TU104GL_Tesla_T4: 1 # limits count of GPU must be equal to requests
          requests:
            cpu: "4"
            memory: 8Gi
            nvidia.com/TU104GL_Tesla_T4: 1
```

The above example shows that two cards were used

It doesn't meet the expectation. It seems strange. Is there any better way to express it

**Comment by sseetharaman6** [comment]
@ZP-AlwaysWin , In your example, you are requesting just 1 GPU and the requests/limits reflect that as well.  For multiple gpus, please request them like below in the `spec.domain.devices.gpus`  in the VMI spec. This will be translated as suitable number of `requests`  and `limits` by Kubevirt. 
```
gpus:
          - deviceName: nvidia.com/TU104GL_Tesla_T4
            name: gpu1
         - deviceName: nvidia.com/TU104GL_Tesla_T4
            name: gpu2
```
