### ISSUE TITLE
Support KubeVirt interface for device plugins

### ISSUE THREAD

**Issue by vladikr** [NVIDIA/kubevirt-gpu-device-plugin#19]
KubeVirt has recently introduced a stable interface for device plugins[1] with the instruction of [2]  
It now expects the device plugins to provide a list of allocated devices via environment variables that encode the name of the resource with its relevant type.
This is mainly needed for Kubevirt to be able to correlate the allocated devices to its API object.
For example :
```
PCI_RESOURCE_NVIDIA_COM_TU104GL_Tesla_T4=PCIADDRESS1
MDEV_PCI_RESOURCE_NVIDIA_COM_GRID_T4-1Q=UUID1
```

Can now be correlated to the API object

```
spec:
  domain:
    devices:
      gpus:
      - deviceName: nvidia.com/TU104GL_Tesla_T4
        name: gpu1
      - deviceName: nvidia.com/GRID_T4-1Q
        name: gpu2
```

Although KubeVirt still supports the legacy approach, it is essential to make changes in this device plugin for KubeVirt to be able to expand the API to support new features.
For example to expand the Device role tagging. [3]

[1] https://github.com/kubevirt/kubevirt/blob/master/docs/devel/host-devices-and-device-plugins.md (KubeVirt interface for device plugins)
[2] https://github.com/kubevirt/kubevirt/pull/3937
[3] https://kubevirt.io/user-guide/virtual_machines/startup_scripts/#device-role-tagging
