### ISSUE TITLE
Cannot pull docker image quay.io/nvidia/vfio-device-plugin:demo

### ISSUE THREAD

**Issue by x8091** [NVIDIA/kubevirt-gpu-device-plugin#2]
The image is located at **quay.io/nvidia/vfio-device-plugin:demo**
However we cannot pull it, error message `Error response from daemon: unauthorized: access to the requested resource is not authorized`

Please help to check

I tried to compile the source code but a lot of error messages throw out:
`cannot find package "k8s.io/kubernetes/pkg/kubelet/apis/deviceplugin/v1beta1" in any of:`

**Comment by visheshtanksale** [comment]
We are in the process of making the docker repository public. In mean time you can use the make to build your own image. You will have to place the code in the `GOPATH` and use `make` to build the code.
I feel the build process is complicated. I will soon push a change to update build process to be simpler.

**Comment by x8091** [comment]
Thanks, I can build the docker image now.
After deploy gpu device plugin into our k8s cluster, I can see GPU resource shows up as following:
```
Capacity:
 cpu:                                12
 devices.kubevirt.io/kvm:            110
 devices.kubevirt.io/tun:            110
 devices.kubevirt.io/vhost-net:      110
 ephemeral-storage:                  478829376Ki
 hugepages-1Gi:                      0
 hugepages-2Mi:                      0
 memory:                             65873288Ki
 nvidia.com/GP107_GeForce_GTX_1050:  1
 nvidia.com/gpu:                     0
 pods:                               110
Allocatable:
 cpu:                                12
 devices.kubevirt.io/kvm:            110
 devices.kubevirt.io/tun:            110
 devices.kubevirt.io/vhost-net:      110
 ephemeral-storage:                  441289152191
 hugepages-1Gi:                      0
 hugepages-2Mi:                      0
 memory:                             65770888Ki
 nvidia.com/GP107_GeForce_GTX_1050:  1
 nvidia.com/gpu:                     0
 pods:                               110
```

I tried to create a VM with following specs:
```
        resources:
          limits:
            nvidia.com/GP107_GeForce_GTX_1050: 1
          requests:
            memory: 4096M
            nvidia.com/GP107_GeForce_GTX_1050: 1
```
The VM already scheduled on a worker node which has GPU available however inside that VM I can't see the NVIDIA GPU, using `lspci`:
```
00:00.0 Host bridge: Intel Corporation 82G33/G31/P35/P31 Express DRAM Controller
00:01.0 VGA compatible controller: Device 1234:1111 (rev 02)
00:02.0 PCI bridge: Red Hat, Inc. QEMU PCIe Root port
00:02.1 PCI bridge: Red Hat, Inc. QEMU PCIe Root port
00:02.2 PCI bridge: Red Hat, Inc. QEMU PCIe Root port
00:02.3 PCI bridge: Red Hat, Inc. QEMU PCIe Root port
00:02.4 PCI bridge: Red Hat, Inc. QEMU PCIe Root port
00:1f.0 ISA bridge: Intel Corporation 82801IB (ICH9) LPC Interface Controller (rev 02)
00:1f.2 SATA controller: Intel Corporation 82801IR/IO/IH (ICH9R/DO/DH) 6 port SATA Controller [AHCI mode] (rev 02)
00:1f.3 SMBus: Intel Corporation 82801I (ICH9 Family) SMBus Controller (rev 02)
01:00.0 Ethernet controller: Red Hat, Inc. Virtio network device (rev 01)
02:00.0 Communication controller: Red Hat, Inc. Virtio console (rev 01)
03:00.0 SCSI storage controller: Red Hat, Inc. Virtio block device (rev 01)
04:00.0 SCSI storage controller: Red Hat, Inc. Virtio block device (rev 01)
```

**What is wrong here**?

Inside **virt-launcher** pod I can NOT see this option **-device vfio-pci,host=01:00.0,id=hostdev0,bus=pci.2**. This option should be there to make GPU passthrough work, isn't it?

Furthermore, `kubectl logs -f pod/virt-launcher-gpu-vm-ncbqp  -c compute` indicates a lot of error related to permission:
```
{"component":"virt-launcher","level":"error","msg":"Failed to open config space file '/sys/bus/pci/devices/0000:00:00.0/config': Read-only file system","pos":"virPCIDeviceConfigOpen:298","subcomponent":"libvirt","thread":"64","timestamp":"2019-10-21T19:04:22.342000Z"}
{"component":"virt-launcher","level":"error","msg":"Failed to open config space file '/sys/bus/pci/devices/0000:00:01.0/config': Read-only file system","pos":"virPCIDeviceConfigOpen:298","subcomponent":"libvirt","thread":"64","timestamp":"2019-10-21T19:04:22.342000Z"}
{"component":"virt-launcher","level":"error","msg":"Failed to open config space file '/sys/bus/pci/devices/0000:01:00.0/config': Read-only file system","pos":"virPCIDeviceConfigOpen:298","subcomponent":"libvirt","thread":"64","timestamp":"2019-10-21T19:04:22.345000Z"}
```

Is this root cause for the issue? How can we grant permission for virt-launcher to access IOMMU group?

**Comment by visheshtanksale** [comment]
Can you refer to the example Kubevirt vmi yaml here https://github.com/kubevirt/kubevirt/blob/master/examples/vmi-gpu.yaml to create the kubevirt VM?

**Comment by x8091** [comment]
I tried already, using that the VM didn't get schedule on any worker nodes.

Do we need to run virt-launcher with privileged mode? Looks like it can't access IOMMU group.

**Comment by visheshtanksale** [comment]
Can you provide the output of `kubectl describe node <node-name>` for the node which has GPU. Also can you provide me the VM/VMI yaml?
No you dont have to run the virt-launcher in privileged mode.

**Comment by x8091** [comment]
I already provided these information above. Here it is:
```
Capacity:
 cpu:                                12
 devices.kubevirt.io/kvm:            110
 devices.kubevirt.io/tun:            110
 devices.kubevirt.io/vhost-net:      110
 ephemeral-storage:                  478829376Ki
 hugepages-1Gi:                      0
 hugepages-2Mi:                      0
 memory:                             65873288Ki
 nvidia.com/GP107_GeForce_GTX_1050:  1
 nvidia.com/gpu:                     0
 pods:                               110
Allocatable:
 cpu:                                12
 devices.kubevirt.io/kvm:            110
 devices.kubevirt.io/tun:            110
 devices.kubevirt.io/vhost-net:      110
 ephemeral-storage:                  441289152191
 hugepages-1Gi:                      0
 hugepages-2Mi:                      0
 memory:                             65770888Ki
 nvidia.com/GP107_GeForce_GTX_1050:  1
 nvidia.com/gpu:                     0
 pods:                               110
```

I tried to create a VM with following specs:

```
        resources:
          limits:
            nvidia.com/GP107_GeForce_GTX_1050: 1
          requests:
            memory: 4096M
            nvidia.com/GP107_GeForce_GTX_1050: 1
```

**Comment by visheshtanksale** [comment]
You have to add following in the `domain.devices` of you VMI.
```
      gpus:
      - deviceName: nvidia.com/GP107_GeForce_GTX_1050
        name: gpu1
```
If you are on kubevirt v0.22.0 you will also have to enable to feature gate for GPU pass through. You can do that by creating a configmap as below
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubevirt-config
  namespace: kubevirt
  labels:
    kubevirt.io: ""
data:
  feature-gates: "GPU"
```

**Comment by x8091** [comment]
I already enabled GPU feature gate.

> You have to add following in the domain.devices of you VMI.
> 
>       gpus:
>       - deviceName: nvidia.com/GP107_GeForce_GTX_1050
>         name: gpu1

As mentioned above, with this section added, the VM is no longer can be scheduled

**Comment by visheshtanksale** [comment]
Do you mean the virt-launcher pod does not get scheduled? Can you provide me the scheduling error you get? Can you please provide `kubectl describe` output of the virt-launcher pod?

**Comment by x8091** [comment]
Here is full message:

```
Status:
  Conditions:
    Last Probe Time:       <nil>
    Last Transition Time:  2019-10-22T07:12:47Z
    Message:               0/10 nodes are available: 10 Insufficient nvidia.com/GP107_GeForce_GTX_1050, 3 Insufficient devices.kubevirt.io/kvm, 3 Insufficient devices.kubevirt.io/tun, 3 Insufficient devices.kubevirt.io/vhost-net, 3 node(s) didn't match node selector.
    Reason:                Unschedulable
    Status:                False
    Type:                  PodScheduled
  Phase:                   Scheduling
  Qos Class:               Burstable
Events:
  Type    Reason            Age    From                       Message
  ----    ------            ----   ----                       -------
  Normal  SuccessfulCreate  6m26s  virtualmachine-controller  Created virtual machine pod virt-launcher-gpu-vm-hainh-vsmpt
```

It keeps saying `Insufficient nvidia.com/GP107_GeForce_GTX_1050` while we have 2 nodes with GPU.

If we don't add 
```
gpus:
  - deviceName: nvidia.com/GP107_GeForce_GTX_1050
    name: gpu1
```
then the VM can run but `lspci` show nothing

**Comment by x8091** [comment]
Seems like we had issue while upgrading kubevirt from v0.17.1 to v0.22.0, deploying a fresh cluster using v0.22.0 we can now create VM with GPU deviceName syntax as you mentioned, here is yaml file

```
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: gpu-vm
spec:
  running: true
  template:
    metadata:
      labels: 
        kubevirt.io/size: large
        kubevirt.io/domain: foobar
    spec:
      domain:
        cpu:
          cores: 4
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
          interfaces:
          - name: default
            bridge: {}
          gpus:
          - deviceName: nvidia.com/GP107_GeForce_GTX_1050
            name: gpu1
        resources:
          requests:
            memory: 4096M
      networks:
      - name: default
        pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: registry:8091/kubevirt-ubuntu-18.04
```

Inside the VM, we can see GPU info using `lspci`:

```
00:00.0 Host bridge: Intel Corporation 82G33/G31/P35/P31 Express DRAM Controller
00:01.0 VGA compatible controller: Device 1234:1111 (rev 02)
00:02.0 PCI bridge: Red Hat, Inc. QEMU PCIe Root port
00:02.1 PCI bridge: Red Hat, Inc. QEMU PCIe Root port
00:02.2 PCI bridge: Red Hat, Inc. QEMU PCIe Root port
00:02.3 PCI bridge: Red Hat, Inc. QEMU PCIe Root port
00:02.4 PCI bridge: Red Hat, Inc. QEMU PCIe Root port
00:02.5 PCI bridge: Red Hat, Inc. QEMU PCIe Root port
00:1f.0 ISA bridge: Intel Corporation 82801IB (ICH9) LPC Interface Controller (rev 02)
00:1f.2 SATA controller: Intel Corporation 82801IR/IO/IH (ICH9R/DO/DH) 6 port SATA Controller [AHCI mode] (rev 02)
00:1f.3 SMBus: Intel Corporation 82801I (ICH9 Family) SMBus Controller (rev 02)
01:00.0 PCI bridge: Red Hat, Inc. Device 000e
02:01.0 VGA compatible controller: NVIDIA Corporation GP107 [GeForce GTX 1050] (rev a1)
03:00.0 Ethernet controller: Red Hat, Inc. Virtio network device (rev 01)
04:00.0 Communication controller: Red Hat, Inc. Virtio console (rev 01)
05:00.0 SCSI storage controller: Red Hat, Inc. Virtio block device (rev 01)
06:00.0 SCSI storage controller: Red Hat, Inc. Virtio block device (rev 01)
```

However, after installing nvidia-driver-430, execute `nvidia-smi` got following error:
`Unable to determine the device handle for GPU 0000:02:01.0: Unknown Error`
