### ISSUE TITLE
NVIDIA vGPU failed on windows 10 with driver error code 12

### ISSUE THREAD

**Issue by mokarage** [NVIDIA/kubevirt-gpu-device-plugin#32]
I raised the same issue https://github.com/kubevirt/kubevirt/issues/7109. I was wondering if I'm missing some step or latest NVIDIA drivers (13.1) are not working in these scenarios. 

Here are my deployment configs and versioning:
k8s: v1.21.7
kubevirt: 0.48.1
NVIDIA kubevirt device plugin: v1.1.0
NVIDIA drivers: NVIDIA-GRID-Linux-KVM-470.82-470.82.01-472.39

vm.yml:
```yaml
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: windows10-iso
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/domain: windows10-iso
    spec:
      domain:
        cpu:
          cores: 2
        devices:
          gpus:
          - deviceName: nvidia.com/GRID_M10-0Q
            name: vgpu1
          disks:
          - bootOrder: 1
            cdrom:
              bus: virtio
            name: cdromiso
          - bootOrder: 2
            disk:
              bus: virtio
            name: harddrive
          - cdrom:
              bus: sata
            name: virtiocontainerdisk

          rng: {}
        features:
          acpi: {}
          apic: {}
          hyperv:
            relaxed: {}
            spinlocks:
              spinlocks: 8191
            vapic: {}
        clock:
          utc: {}
          timer:
            hpet:
              present: false
            pit:
              tickPolicy: delay
            rtc:
              tickPolicy: catchup
            hyperv: {}

        machine:
          type: ""
        resources:
          requests:
            memory: 8Gi
      volumes:
      - name: cdromiso
        persistentVolumeClaim:
          claimName: upload-win10-dv
      - name: harddrive
        persistentVolumeClaim:
          claimName: winhd0
      - containerDisk:
          image: kubevirt/virtio-container-disk
        name: virtiocontainerdisk
```
kubevirt-cr.yaml:
```yaml
apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  certificateRotateStrategy: {}
  configuration:
    mediatedDevicesConfiguration:
      mediatedDevicesTypes:
        - nvidia-36
    permittedHostDevices:
      mediatedDevices:
      - mdevNameSelector: "GRID M10-0Q"
        resourceName: "nvidia.com/GRID_M10-0Q"
        externalResourceProvider: true

    developerConfiguration:
      featureGates: 
        - GPU
        - DataVolumes
        - HostDevices
        - CPUManager
        - HostDisk
        - ExperimentalVirtiofsSupport
        - CPUNodeDiscovery
        - HypervStrictCheck
  customizeComponents: {}
  imagePullPolicy: IfNotPresent
  workloadUpdateStrategy: {}
```
