### ISSUE TITLE
Windows VM - no bootable medium

### ISSUE THREAD

**Issue by tssavita** [NVIDIA/kubevirt-gpu-device-plugin#6]
OS: Ubuntu 19.04
Kubevirt Version: v0.22.0
Kubernetes Version: 1.17.0

What happened: 
VM gets Running, but when connecting to it via VNC, but doesn't detect a bootable disk. It shows "Boot failed: not a bootable disk". I downloaded the Windows Server 2012 image downloaded from: https://www.microsoft.com/en-us/evalcenter/evaluate-windows-server-2012.

![Screenshot from 2019-12-12 13-37-44](https://user-images.githubusercontent.com/2744118/70705803-04102480-1cd5-11ea-9dfb-70f6ac718509.png)

The same disk successfully boots when creating a VM on Qemu. 
I have also tried this for: 
1. A preexisting windows VM qcow2 image. 
2. Wrapping windows qcow2 image in a container image and pushing Docker image to remote repo. 

All yield the same result - no bootable medium. 

The first suspicion was that the firmware in Kubevirt was not detecting the image as bootable. Also tried specifying the firmware to q35. 
And setting the bootorder for the disk. But no success. 

My VMI yaml file: (which I found from )
```
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  labels:
    special: win12_eval
  name: win12k_eval
spec:
  domain:
    devices:
      disks:
      - disk:
          bus: sata
        name: host-disk
    machine:
      type: ""
    resources:
      requests:
        memory: 15G
  terminationGracePeriodSeconds: 0
  volumes:
  - hostDisk:
      path: <path-on-host>/win12_eval.img
      type: Disk
    name: host-disk
status: {}                    
```
Any hints on why this happens?
