### ISSUE TITLE
Passthrough of more than 2 GPUs doesn't work

### ISSUE THREAD

**Issue by dhruvik7** [NVIDIA/kubevirt-gpu-device-plugin#67]
When I increase the number of GPUs to passthrough in my VM spec, it maxes out at 2 GPUs actually being accessible (in lspci) inside the VM, although Kubernetes marks the correct number of GPU requests/limits on the node. Is there a limit of 2 GPUs being passed through or am I doing something wrong?

**Comment by dhruvik7** [comment]
Here's the VM spec
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  creationTimestamp: 2018-07-04T15:03:08Z
  generation: 1
  labels:
    kubevirt.io/os: linux
  name: vm-quad-test
spec:
  running: true
  template:
    metadata:
      creationTimestamp: null
      labels:
        kubevirt.io/domain: vm-quad-test
    spec:
      domain:
        cpu:
          cores: 4
        devices:
          disks:
          - disk:
              bus: virtio
            name: disktrio
          - disk:
              bus: virtio
            name: cloudinitdisk
          gpus:
            - name: gpu1
              deviceName: nvidia.com/GA102_GEFORCE_RTX_3090
            - name: gpu2
              deviceName: nvidia.com/GA102_GEFORCE_RTX_3090
            - name: gpu3
              deviceName: nvidia.com/GA102_GEFORCE_RTX_3090
            - name: gpu4
              deviceName: nvidia.com/GA102_GEFORCE_RTX_3090
        machine:
          type: q35
        resources:
          requests:
            memory: 8192M
            nvidia.com/GA102_GEFORCE_RTX_3090: 4
          limits:
            nvidia.com/GA102_GEFORCE_RTX_3090: 4
      volumes:
      - dataVolume:
          name: ubuntu-dv-quad
        name: disktrio
      - name: cloudinitdisk
        cloudInitNoCloud:
          networkData: |
            version: 2
            ethernets:
              enp1s0:
                dhcp4: true
              enp1s1:
                dhcp4: true
          userData: |
            #cloud-config
            password: ubuntu
            chpasswd: { expire: False }
            ssh_pwauth: True
  dataVolumeTemplates:
  - metadata:
      name: ubuntu-dv-quad
    spec:
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 35Gi
      source:
        registry:
          url: "docker://tedezed/ubuntu-container-disk:20.0"
``` 

Here's the allocatable and capacity from the node description
Capacity:
  cpu:                                256
  devices.kubevirt.io/kvm:            1k
  devices.kubevirt.io/tun:            1k
  devices.kubevirt.io/vhost-net:      1k
  ephemeral-storage:                  1134737624Ki
  hugepages-1Gi:                      0
  hugepages-2Mi:                      0
  memory:                             247414732Ki
  nvidia.com/GA102_GEFORCE_RTX_3090:  8
  nvidia.com/gpu:                     0
  pods:                               110
Allocatable:
  cpu:                                255900m
  devices.kubevirt.io/kvm:            1k
  devices.kubevirt.io/tun:            1k
  devices.kubevirt.io/vhost-net:      1k
  ephemeral-storage:                  1045774192547
  hugepages-1Gi:                      0
  hugepages-2Mi:                      0
  memory:                             247050188Ki
  nvidia.com/GA102_GEFORCE_RTX_3090:  8
  nvidia.com/gpu:                     0
  pods:                               110


Running `lspci` in the resulting VM shows only 2 GPUs passed through
06:00.0 VGA compatible controller [0300]: NVIDIA Corporation Device [10de:2204] (rev a1)
	Subsystem: ASUSTeK Computer Inc. Device [1043:87d5]
	Kernel modules: nvidiafb
07:00.0 Audio device [0403]: NVIDIA Corporation Device [10de:1aef] (rev a1)
	Subsystem: ASUSTeK Computer Inc. Device [1043:87d5]
08:00.0 VGA compatible controller [0300]: NVIDIA Corporation Device [10de:2204] (rev a1)
	Subsystem: ASUSTeK Computer Inc. Device [1043:87d5]
	Kernel modules: nvidiafb
09:00.0 Audio device [0403]: NVIDIA Corporation Device [10de:1aef] (rev a1)
	Subsystem: ASUSTeK Computer Inc. Device [1043:87d5]
